version: '3.8'

services:
  services-api:
    build: .
    container_name: services-api
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./generated_files:/app/generated_files
    networks:
      - docker_default
    restart: unless-stopped

networks:
  docker_default:
    external: true
